import Anthropic from "@anthropic-ai/sdk";
import { env } from "@/lib/env";
import { type ProjectType, PROJECT_TYPE_LABELS } from "@/lib/presets";

const client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });

export interface ScopeInput {
  clientName: string;
  projectType: ProjectType;
  deliverables: string[];
  exclusions: string[];
  acceptanceCrit: string[];
  assumptions: string[];
  timeline: string;
  budget: string;
}

export interface GeneratedDocuments {
  proposalMd: string;
  sowMd: string;
  changeReqEmail: string;
}

const SYSTEM_PROMPT = `You are a professional freelance proposal writer. You produce polished, clear Proposals and Statements of Work (SOW) that protect the freelancer's scope. Your writing is professional but approachable — friendly, not legalistic.

IMPORTANT: All documents are for business communication purposes only. They are NOT legal advice. Include "Not legal advice." in the footer of every document you generate.

Format rules:
- Use Markdown with proper headings (## and ###)
- Be concise and clear — no filler phrases
- Use [PLACEHOLDER] for any value the freelancer should fill in (e.g. [Date], [Your Name], [Client Signature])
- The Proposal must end with a signature block: spaces for freelancer name/date and client name/date
- The SOW must include a "Scope Change Process" section with best-practice scope-protection language, and a "Payment Terms" section specifying deposit (50% upfront), milestone payments, and final payment on acceptance
- The Change Request Email should be short (under 150 words), reference the original SOW, and state that work will pause until a change order is signed`;

function buildUserPrompt(input: ScopeInput): string {
  const projectLabel = PROJECT_TYPE_LABELS[input.projectType];

  return `Generate three documents for a freelance project. Use EXACTLY this structure in your response:

<proposal>
[Full professional proposal in Markdown]
</proposal>

<sow>
[Full Statement of Work in Markdown]
</sow>

<change_request>
[Change Request Email template in Markdown — client fills in [brackets]]
</change_request>

---

PROJECT DETAILS:
- Client Name: ${input.clientName}
- Project Type: ${projectLabel}
- Timeline: ${input.timeline}
- Budget: ${input.budget}

SCOPE (use these exactly — do not invent new scope):

**Deliverables:**
${input.deliverables.map((d) => `- ${d}`).join("\n")}

**Exclusions (not included):**
${input.exclusions.map((e) => `- ${e}`).join("\n")}

**Acceptance Criteria:**
${input.acceptanceCrit.map((a) => `- ${a}`).join("\n")}

**Assumptions:**
${input.assumptions.map((a) => `- ${a}`).join("\n")}

---

For the Proposal: write a professional client-facing proposal introducing the project, summarizing deliverables and timeline, and ending with a clear call to action (sign and return).

For the SOW: write a detailed Statement of Work with sections for Deliverables, Exclusions, Acceptance Criteria, Assumptions, Timeline, Payment Terms, and a Scope Change Process section explaining how changes will be handled (written notice required, change order pricing, work paused until approved).

For the Change Request Email: write a short professional email template the freelancer sends to a client when the client requests work outside the original scope.

End each document with: *Not legal advice. Generated by ScopeShield · scopeshield.io*`;
}

/** Parse the three document sections from Claude's response */
function parseDocuments(text: string): GeneratedDocuments {
  const extract = (tag: string): string => {
    const match = text.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`));
    if (!match) throw new Error(`Missing <${tag}> section in AI response`);
    return match[1].trim();
  };

  return {
    proposalMd: extract("proposal"),
    sowMd: extract("sow"),
    changeReqEmail: extract("change_request"),
  };
}

export async function generateDocuments(
  input: ScopeInput
): Promise<GeneratedDocuments> {
  const start = Date.now();

  const message = await client.messages.create({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 8000,
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: buildUserPrompt(input) }],
  });

  const text =
    message.content[0].type === "text" ? message.content[0].text : "";

  console.log(
    JSON.stringify({
      event: "claude_generate",
      model: "claude-haiku-4-5-20251001",
      input_tokens: message.usage.input_tokens,
      output_tokens: message.usage.output_tokens,
      duration_ms: Date.now() - start,
    })
  );

  return parseDocuments(text);
}
