import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Footer,
  AlignmentType,
  BorderStyle,
  PageBreak,
} from "docx";

interface DocxSection {
  title: string;
  content: string;
}

interface DocxOptions {
  watermark: boolean;
  title: string;
  sections: DocxSection[];
}

/** Parse basic markdown into docx Paragraph nodes.
 * Supports: # ## ### headings, **bold**, bullet lists (- item), blank lines.
 */
function parseMarkdown(md: string): Paragraph[] {
  const lines = md.split("\n");
  const paragraphs: Paragraph[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (line.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(4),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 80 },
        })
      );
    } else if (line.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(3),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 },
        })
      );
    } else if (line.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(2),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        })
      );
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: parseInline(line.slice(2)),
          spacing: { before: 40, after: 40 },
        })
      );
    } else if (line === "---" || line === "***") {
      paragraphs.push(
        new Paragraph({
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 6, color: "CCCCCC" },
          },
          spacing: { before: 200, after: 200 },
        })
      );
    } else if (line === "") {
      paragraphs.push(new Paragraph({ spacing: { before: 80, after: 80 } }));
    } else {
      paragraphs.push(
        new Paragraph({
          children: parseInline(line),
          spacing: { before: 60, after: 60 },
        })
      );
    }
  }

  return paragraphs;
}

/** Parse inline markdown: **bold**, *italic*, plain text */
function parseInline(text: string): TextRun[] {
  const runs: TextRun[] = [];
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g);
  for (const part of parts) {
    if (part.startsWith("**") && part.endsWith("**")) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true }));
    } else if (part.startsWith("*") && part.endsWith("*")) {
      runs.push(new TextRun({ text: part.slice(1, -1), italics: true }));
    } else {
      runs.push(new TextRun({ text: part }));
    }
  }
  return runs;
}

function buildFooter(watermark: boolean): Footer {
  const text = watermark
    ? "Generated by ScopeShield · Not legal advice · scopeshield.io"
    : "Not legal advice · scopeshield.io";

  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text,
            size: 16,
            color: "888888",
            italics: true,
          }),
        ],
      }),
    ],
  });
}

/** Generate a DOCX Buffer from structured sections.
 * Each section starts on a new page with a section title.
 */
export async function generateDocx(
  opts: DocxOptions
): Promise<Buffer> {
  const children: Paragraph[] = [
    // Document title
    new Paragraph({
      text: opts.title,
      heading: HeadingLevel.TITLE,
      spacing: { before: 0, after: 600 },
    }),
  ];

  opts.sections.forEach((section, i) => {
    // Page break before every section except the first
    if (i > 0) {
      children.push(
        new Paragraph({
          children: [new PageBreak()],
        })
      );
    }

    // Section label (e.g. "PROPOSAL", "STATEMENT OF WORK")
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: section.title.toUpperCase(),
            bold: true,
            size: 24,
            color: "1D4ED8",
          }),
        ],
        spacing: { before: 0, after: 300 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 8, color: "DBEAFE" },
        },
      })
    );

    children.push(...parseMarkdown(section.content));
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        footers: {
          default: buildFooter(opts.watermark),
        },
        children,
      },
    ],
  });

  return Packer.toBuffer(doc);
}
