export default function TermsPage() {
  return (
    <div className="py-20 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-8">Last updated: March 2026</p>

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-8">
          <p className="text-amber-800 font-semibold text-sm">
            ⚠️ NOT LEGAL ADVICE: ScopeShield generates documents for business communication purposes only.
            Nothing on this site or generated by this service constitutes legal advice. Consult a qualified
            attorney for legal guidance specific to your situation.
          </p>
        </div>

        <div className="space-y-8 text-gray-600 leading-relaxed">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">1. Service description</h2>
            <p>
              ScopeShield is a software tool that uses AI to generate business documents (proposals,
              statements of work, and email templates) based on information you provide. These documents
              are intended to help freelancers communicate scope clearly with clients. They are not
              legal contracts, not legal advice, and do not create any attorney-client relationship.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">2. Acceptable use</h2>
            <p>
              You may use ScopeShield for legitimate business purposes. You agree not to use the service
              to generate fraudulent documents, impersonate others, or violate any applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">3. Subscriptions and billing</h2>
            <p>
              Free plan: 3 proposals per month at no charge. Pro plan: unlimited proposals billed monthly
              or annually. Subscriptions auto-renew. Cancel anytime via the billing portal. No refunds
              for partial billing periods.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">4. Limitation of liability</h2>
            <p>
              ScopeShield is provided &ldquo;as is&rdquo; without warranties of any kind. We are not responsible
              for any outcome resulting from the use of documents generated by this service, including but
              not limited to disputes with clients, financial losses, or unenforceable agreements.
              Your use of generated documents is entirely at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">5. Intellectual property</h2>
            <p>
              You own the content you input and the documents generated for your account. ScopeShield
              retains no rights to your generated documents.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">6. Changes to terms</h2>
            <p>
              We may update these terms at any time. Continued use of the service after changes constitutes
              acceptance of the updated terms.
            </p>
          </section>
        </div>

        <p className="text-sm text-gray-400 border-t pt-6 mt-10">
          Not legal advice. For questions, contact us at legal@scopeshield.io
        </p>
      </div>
    </div>
  );
}
