import { auth } from "@clerk/nextjs/server";
import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import { db } from "@/lib/db";
import { canDownloadClean } from "@/lib/entitlements";
import ProposalPreview from "@/components/proposal-preview";

export default async function ProposalPage({
  params,
}: {
  params: { id: string };
}) {
  const { userId } = await auth();
  if (!userId) redirect("/sign-in");

  const [proposal, isClean] = await Promise.all([
    db.proposal.findUnique({
      where: { id: params.id },
      select: {
        id: true,
        userId: true,
        clientName: true,
        projectType: true,
        proposalMd: true,
        sowMd: true,
        changeReqEmail: true,
        createdAt: true,
      },
    }),
    canDownloadClean(userId),
  ]);

  if (!proposal || proposal.userId !== userId) notFound();

  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex items-center gap-4 mb-6">
        <Link href="/dashboard" className="text-sm text-gray-500 hover:text-gray-700">
          ← Dashboard
        </Link>
        <h1 className="text-2xl font-bold text-gray-900 flex-1">
          {proposal.clientName}
        </h1>
        <a
          href={`/api/download/${proposal.id}`}
          className="flex items-center gap-2 px-5 py-2.5 bg-brand-600 text-white text-sm rounded-xl hover:bg-brand-700 transition-colors"
        >
          ↓ Download DOCX
          {!isClean && (
            <span className="text-xs bg-brand-500 px-1.5 py-0.5 rounded">Free</span>
          )}
        </a>
      </div>

      {!isClean && (
        <div className="mb-6 bg-amber-50 border border-amber-200 rounded-xl p-4 flex items-center justify-between">
          <p className="text-sm text-amber-800">
            Free plan: downloads include a ScopeShield watermark.
          </p>
          <Link
            href="/pricing"
            className="text-sm font-medium text-amber-900 underline ml-4"
          >
            Upgrade to remove →
          </Link>
        </div>
      )}

      <ProposalPreview
        proposalMd={proposal.proposalMd}
        sowMd={proposal.sowMd}
        changeReqEmail={proposal.changeReqEmail}
      />

      <p className="mt-8 text-xs text-gray-400 text-center">
        Not legal advice. Generated by ScopeShield · scopeshield.io
      </p>
    </div>
  );
}
